### PR TITLE
Update languages.dart

### PR DESCRIPTION
**Pull request by CYAXXX**
Codes and typo corrections for kurmanji kurdish and sorani kurdish.
ku for kurmanji kurdish
ckb for sorani kurdish

### CODE REVIEW

**Comment by Artx-II** [comment]
I will disable Sorani Kurdish since currently there is no translation file

**Comment by CYAXXX** [comment]
> I will disable Sorani Kurdish since currently there is no translation file

Fair enough, thank you

**Comment by Artx-II** [comment]
Can you point me which file is that? Class "LanguageCkb" doesn't seem to exist

**Comment by CYAXXX** [comment]
> Can you point me which file is that? Class "LanguageCkb" doesn't seem to exist

https://github.com/SongTube/SongTube-App/blob/development/lib/internal/languages/languageKu.dart if I'm not misunderstanding you this one is for sorani Kurdish under this code (ku) which must be changed for (ckb)

**Comment by Artx-II** [comment]
That one is already referenced and enabled on the app languages

But your changes includes a new "LanguageCkb" class/file that doesn't exist, hence why I disabled it

Also there is a language class/file named "LanguageKmr" that is currently unused

**Pull request merged**
