### PR TITLE
Fixed volume/brightness/overlay issues on player

### PR DESCRIPTION
**Pull request by ishanvaghani**
**Fixed below issues on player screen**
- Fixed volume gesture issue
- Optimised brightness gesture
- Fixed overlay visibility issue

### CODE REVIEW

**Comment by ishanvaghani** [comment]
@Artx-II can you please check and merge?

**Comment by Artx-II** [comment]
Tested and works fine, thank you!

**Comment by ishanvaghani** [comment]
Thank you. This is my first flutter contribution.

**Comment by Artx-II** [comment]
> Thank you. This is my first flutter contribution.

That's awesome, I appreciate it a lot!

**Pull request merged**
