### PR TITLE
Updated and fixed dependencies

### PR DESCRIPTION
**Pull request by harshmandan**

### CODE REVIEW

**Comment by harshmandan** [comment]
Bumped versions, everything works fine. Though you can test once on your side as well.
Handled the package changes as well.

Could not resolve the `flutter_http` package version. Can you fix the version for that?

## Findings
Only one dependency is holding back most of the other dependencies from being updated to the latest version:
`flutter_audio_query`
Consider using alternatives such as:
`audiofileplayer `
or
`audiotagger`

Thanks 🙏

**Comment by harshmandan** [comment]
Added another commit, which uses a fork of the package `flutter_audio_query` (the original's development seems kind of abandoned).
The fork has null-safety update which allows us to bump all the other packages to the latest versions!

App should be more stable and performant now!

**Comment by harshmandan** [comment]
I'm confused about one thing. I cannot update the package `flutter_html` as it clashes with some other package. But I could find the reference to the package anywhere.
image

Do you know anything about this @Artx-II

**Comment by Artx-II** [comment]
Amazing work, thank you! 😄

**Pull request merged**
